### PR TITLE
Updates, bug fixes, and cleanup

### PR DESCRIPTION
**Pull request by mvanderkamp**
Add a 'change' property to the emitted data to allow users to distinguish between them (also this is just generally a useful piece of data).

### CODE REVIEW

**Comment by mvanderkamp** [comment]
My apologies, I got carried away and did a bunch of cleanup and fixing, and forgot this was still open when I pushed to my master branch. Here's a summary of the changes thus far:

- Fix the 'Expand / Pinch' bug by merging them with Distance into a single Pinch class that reports 'change' in its output.
- Fix the jitter that was seen in 'Rotate' by fixing a bug in the arbiter function. This bug was caused because the arbiter accessed the ID directly instead of using getId().
- General fixes to the use of Array prototype methods. There were several places where a solution was hacked together instead of using the appropriate prototype method (e.g. using map() when a forEach() would do, or using forEach() and using a condition to decide whether to push to an external array when filter() or reduce() would have sufficed). This should allow for better runtime optimization of the code by JavaScript engines.
- Add a 'change' field to the output from Pan events.

**Comment by mike-schultz** [comment]
@mvanderkamp Just wanted to pop in and say thanks for the contributions. We're on a deadline crunch for one of our products right now but will review this sometime this week / early next!

**Comment by hackhat** [comment]
This is very useful, thanks.

**Comment by Hinashou** [comment]
@mike-schultz Is it possible to get a new release out there? Seems like a few things have been merged that aren't in the latest release.

**Pull request merged**
