### PR TITLE
Swipe: added duration and distance to the returned info on swipe

### PR DESCRIPTION
**Pull request by AquiGorka**
I needed this info for a project of mine, I think it comes in handy if needed.

Amazing library by the way, thanks!

### CODE REVIEW

**Comment by mike-schultz** [comment]
Thanks for contributing! LGTM!

**Comment by AquiGorka** [comment]
@mike-schultz will you let me know when you release the new version to `npm` with the changes?

**Comment by mike-schultz** [comment]
Will do! We are starting development on this again this week, so we’ll be making some minor changes and bugfixes to release a new version very shortly

**Comment by mike-schultz** [comment]
@AquiGorka On npm as 1.0.6!

**Pull request merged**
