### PR TITLE
Add Server Side Rendering Support

### PR DESCRIPTION
**Pull request by wagoid**
When using the library in an app that uses Server Side Rendering, it breaks, since it tries to add ZingTouch to the window, and window doesn't exist in Node.js.
To fix it, I added UMD support to the webpack config file.

Some people could be using your library like this:
```
// index.js
import 'ZingTouch'

// another-file.js
ZingTouch.Region() //Calling ZingTouch before importing it
```

Because of that, I kept defining ZingTouch to window every time it's available, to make the change backwards compatible.

### CODE REVIEW

**Comment by mike-schultz** [comment]
@wagoid Thanks for the contribution. I tried out the changes, and it looks like setting the build to 'umd' encapsulates the rest of the properties in a default property, causing the library to break. If we ommitted umd and just kept the window check, would that suffice?

**Comment by wagoid** [comment]
hello @mike-schultz! Sorry for that, I imported it incorrectly in `index.js` file. My current project works for both commonjs (without `default`) and es modules (with `default`), so I didn't see any issues.
Regarding your question, it would not work, because in current approach the library doesn't export anything, just assigns something to `window`.
I updated the code and tested, looks like it's correct now (the `Region` is the exported object, not an object with `default` key). Please let me know if there's something else to change 😃

**Comment by markadrake** [comment]
I'd very much like to see this change tested and approved. @wagoid – looks like the branch has conflicts now, do you have time to resolve them so @mike-schultz can test again?

**Comment by wagoid** [comment]
@markadrake thanks for the heads up! Conflicts are fixed now :heavy_check_mark:

**Pull request merged**
